defaults:
  - override hydra/sweeper: optuna

hydra:
  sweeper:
    # optunaの設定
    n_trials: 10
    direction: maximize
    storage: null
    study_name: tpe
    n_jobs: 1
    sampler:
      seed: 0
      _target_: optuna.samplers.TPESampler
    params:
      dummy: 0
      # 実行時に-m オプションをつけると、以下が適用
      # lr: tag(log, interval(0.00001, 0.1))
      # max_epochs: range(10, 300)

# optunaで最適化する評価指標
target: 'test_miou'    

lr: 0.001
max_epochs: 30
batch_size: 4




# EarlyStopping
## patienceエポックにわたり、test_miouがmin_delta以上向上しなかった場合は、訓練を終了する．
patience: 20
min_delta: 0.0


# モデルに関する設定 詳しくは　https://smp.readthedocs.io/en/v0.2.1/
model:

  # アーキテクチャ. Unet, UnetPlusPlus, MAnet, Linknet, FPN...など
  arch: UnetPlusPlus

  # アーキテクチャのバックボーン. resnet18, resnet34, efficientnet-b0...など
  encoder_name: "resnet34"

  # バックボーンと対応関係があるので注意
  encoder_weights: "imagenet"

  # ダウンサンプリングの回数.リサイズの解像度の制限とかかわってきます．
  encoder_depth: 5

  # 入力の次元数. 透過なしカラー画像なので3.
  in_channels: 3

  # 出力のクラス数. 背景と細胞の２種なので1.
  classes: 1

  # 1変数2クラス分類なのでsigmoid.
  activation: sigmoid

# 入力データに関する設定
data:
  # モデルに入力する際に行うリサイズの解像度.2^{ダウンサンプリング回数}で割り切れる数字でなければならない
  img_size: 512
  # 訓練とテストに使うデータセットCSVへのパス．7:3に分けて使用される．csvにはinput列, label列が必要.
  train_test:
    - ./data/raw/part1/pair.csv
  # 推論に使うデータセットCSVへのパス．すべての画像に対する推論結果がmlflowにlogされる.csvにはinput列が必要.
  predict:
    - ./data/raw/part2/pair.csv
    - ./data/raw/part3/pair.csv

dummy: 0