defaults:
  - override hydra/sweeper: optuna

hydra:
  sweeper:
    n_trials: 10
    direction: maximize
    storage: null
    study_name: tpe
    n_jobs: 1
    sampler:
      seed: 0
      _target_: optuna.samplers.TPESampler
    params:
      lr: tag(log, interval(0.00001, 0.1))
      max_epochs: range(10, 300)

    

lr: 0.001
max_epochs: 30
seed: 0
batch_size: 4
model: 
  arch: UnetPlusPlus
  encoder_name: "resnet34"
  in_channels: 3
  classes: 1
  encoder_weights: "imagenet"
  encoder_depth: 5
  activation: sigmoid
data:
  img_size: 512
  train_test:
    - ./data/raw/part1/pair.csv
  predict:
    - ./data/raw/part2/pair.csv
target: 'test_miou'